import { Question } from "./types";

const SHARED_QUESTIONS: Question[] = [
  {
    id: "passport_valid",
    text: "Do you have a valid passport (valid for at least 6 months beyond your intended stay)?",
    helpText: "Your passport must remain valid throughout your stay in Canada.",
    appTypes: ["express-entry", "study-permit"],
    weight: 3,
    flagOnNo: true,
    missingDocLabel: "Valid Passport",
  },
  {
    id: "language_test",
    text: "Have you completed an approved language test (IELTS/CELPIP for English, or TEF/TCF for French)?",
    helpText: "Results must be issued within the last 2 years.",
    appTypes: ["express-entry", "study-permit"],
    weight: 3,
    flagOnNo: true,
    missingDocLabel: "Language Test Results (IELTS/CELPIP/TEF)",
  },
  {
    id: "proof_of_funds",
    text: "Do you have proof of sufficient funds? (Bank statements covering the last 6 months)",
    helpText: "Express Entry minimum: ~CAD $13,310 for a single applicant. Study permit: tuition + living costs.",
    appTypes: ["express-entry", "study-permit"],
    weight: 3,
    flagOnNo: true,
    missingDocLabel: "Proof of Funds (6-month bank statements)",
  },
  {
    id: "consistent_names",
    text: "Does your name appear consistently and identically across all your documents?",
    helpText: "Name discrepancies between passport, bank statements, and credentials are a common rejection trigger.",
    appTypes: ["express-entry", "study-permit"],
    weight: 3,
    flagOnNo: true,
  },
  {
    id: "history_gaps",
    text: "Are all gaps in your employment or personal history (6+ months) accounted for in writing?",
    helpText: "Unexplained gaps in your timeline frequently trigger officer review.",
    appTypes: ["express-entry", "study-permit"],
    weight: 2,
    flagOnNo: true,
  },
  {
    id: "inadmissibility",
    text: "Do you have a criminal record or a serious medical condition that may affect admissibility?",
    helpText: "These may require additional waivers or documentation such as a TRP or Rehabilitation application.",
    appTypes: ["express-entry", "study-permit"],
    weight: 3,
    flagOnNo: false,
    flagOnYes: true,
    category: "hard_fail",
  },
  {
    id: "prior_refusals",
    text: "Have you ever been refused a visa by Canada or any other country?",
    helpText: "Prior refusals increase officer scrutiny. Non-disclosure of refusals is considered misrepresentation.",
    appTypes: ["express-entry", "study-permit"],
    weight: 3,
    flagOnNo: false,
    flagOnYes: true,
    category: "risk_flag",
  },
  {
    id: "refusal_disclosure",
    text: "If you have prior refusals, did you disclose all of them in your application?",
    helpText: "Non-disclosure of prior refusals is misrepresentation and can result in a 5-year ban.",
    appTypes: ["express-entry", "study-permit"],
    weight: 3,
    flagOnNo: true,
    category: "hard_fail",
  },
  {
    id: "travel_history",
    text: "Do you have prior international travel history (e.g., valid or past visas to the US, UK, or Schengen area)?",
    helpText: "Strong travel history to trusted countries boosts credibility with IRCC officers.",
    appTypes: ["express-entry", "study-permit"],
    weight: 1,
    flagOnNo: false,
    boostOnYes: true,
    category: "weakness",
  },
  {
    id: "funds_traceable",
    text: "Are your funds clearly traceable, with no large, unexplained recent deposits?",
    helpText: "Large sudden deposits without a clear source (salary, gift letter, sale) are a major red flag for officers.",
    appTypes: ["express-entry", "study-permit"],
    weight: 3,
    flagOnNo: true,
    category: "hard_fail",
  },
  {
    id: "funds_control",
    text: "Are the funds under your direct control, or properly documented if sponsored by a third party?",
    helpText: "Sponsored funds require a notarized gift/sponsorship letter plus the sponsor's bank statements.",
    appTypes: ["express-entry", "study-permit"],
    weight: 2,
    flagOnNo: true,
    category: "risk_flag",
  },
  {
    id: "doc_authenticity",
    text: "Are all submitted documents genuine, unaltered, and independently verifiable?",
    helpText: "Even minor inconsistencies can trigger a misrepresentation finding, resulting in a 5-year ban.",
    appTypes: ["express-entry", "study-permit"],
    weight: 3,
    flagOnNo: true,
    category: "hard_fail",
  },
  {
    id: "medical_exam",
    text: "Are you prepared to complete an IRCC-approved medical exam if requested?",
    helpText: "Certain countries or programs require an upfront medical exam. Delays here stall or sink applications.",
    appTypes: ["express-entry", "study-permit"],
    weight: 2,
    flagOnNo: true,
    category: "risk_flag",
  },
  {
    id: "police_clearance",
    text: "Can you provide police clearance certificates from all countries where you have lived for 6+ months?",
    helpText: "Missing PCCs are a common cause of delays or refusals.",
    appTypes: ["express-entry", "study-permit"],
    weight: 2,
    flagOnNo: true,
    missingDocLabel: "Police Clearance Certificate(s)",
    category: "risk_flag",
  },
  {
    id: "app_completeness",
    text: "Have you reviewed all required forms for completeness, including all signatures and dates?",
    helpText: "Incomplete or unsigned forms are returned or refused outright without review.",
    appTypes: ["express-entry", "study-permit"],
    weight: 3,
    flagOnNo: true,
    category: "hard_fail",
  },
  {
    id: "officer_perspective",
    text: "Would an officer reviewing your file clearly understand your purpose, finances, and credibility, without any remaining doubts?",
    helpText: "This is the officer's final mental check. If anything looks unclear, address it proactively in a cover letter.",
    appTypes: ["express-entry", "study-permit"],
    weight: 2,
    flagOnNo: true,
    category: "risk_flag",
  },
];

const EXPRESS_ENTRY_QUESTIONS: Question[] = [
  {
    id: "eca",
    text: "Have you obtained an Educational Credential Assessment (ECA) for your foreign degree?",
    helpText: "Required if your highest education was completed outside Canada. Use WES, ICAS, or another IRCC-approved org.",
    appTypes: ["express-entry"],
    weight: 3,
    flagOnNo: true,
    missingDocLabel: "Educational Credential Assessment (ECA)",
  },
  {
    id: "work_experience",
    text: "Do you have at least 1 year of continuous skilled work experience (NOC TEER 0–3) within the last 10 years?",
    helpText: "Must be full-time (or equivalent part-time) paid work experience.",
    appTypes: ["express-entry"],
    weight: 3,
    flagOnNo: true,
    missingDocLabel: "Employment Records / Reference Letters",
  },
  {
    id: "ee_profile",
    text: "Have you created and submitted your Express Entry profile in the IRCC portal?",
    appTypes: ["express-entry"],
    weight: 2,
    flagOnNo: true,
    category: "risk_flag",
  },
  {
    id: "reference_letter_quality",
    text: "Do your employment reference letters include job title, duties, salary, hours per week, and NOC code alignment?",
    helpText: "A common Express Entry rejection reason is reference letters that omit duties or don't match the declared NOC.",
    appTypes: ["express-entry"],
    weight: 3,
    flagOnNo: true,
    missingDocLabel: "Complete Reference Letters (duties, salary, hours, NOC-aligned)",
    category: "hard_fail",
  },
  {
    id: "crs_competitiveness",
    text: "Is your CRS score competitive based on recent draw cutoff scores?",
    helpText: "Check the latest IRCC draw results. Submitting a profile with a score far below recent cutoffs may mean a long wait or no ITA.",
    appTypes: ["express-entry"],
    weight: 2,
    flagOnNo: true,
    category: "weakness",
  },
  {
    id: "pof_exemption_check",
    text: "If you have a qualifying job offer or are applying under the Canadian Experience Class (CEC), are you aware you may be exempt from proof of funds?",
    helpText: "Incorrectly including or excluding proof of funds can flag your application. Confirm your category's requirements.",
    appTypes: ["express-entry"],
    weight: 1,
    flagOnNo: false,
    boostOnYes: true,
    category: "weakness",
  },
];

const STUDY_PERMIT_QUESTIONS: Question[] = [
  {
    id: "letter_of_acceptance",
    text: "Do you have a Letter of Acceptance (LOA) from a Designated Learning Institution (DLI)?",
    helpText: "The institution must appear on the official IRCC Designated Learning Institutions list.",
    appTypes: ["study-permit"],
    weight: 3,
    flagOnNo: true,
    missingDocLabel: "Letter of Acceptance from a DLI",
  },
  {
    id: "ties_home_country",
    text: "Can you demonstrate strong ties to your home country (property, family, existing employment)?",
    helpText: "Officers assess whether you intend to return home after your studies.",
    appTypes: ["study-permit"],
    weight: 2,
    flagOnNo: true,
  },
  {
    id: "sop",
    text: "Have you written a Statement of Purpose (SOP) explaining your study plan and reasons for choosing Canada?",
    appTypes: ["study-permit"],
    weight: 2,
    flagOnNo: true,
    missingDocLabel: "Statement of Purpose (SOP)",
    category: "risk_flag",
  },
  {
    id: "purpose_credibility",
    text: "Does your chosen program logically align with your previous education and career path?",
    helpText: "\"Purpose of visit not credible\" is one of the top 3 study permit refusal reasons. Officers look for a clear academic/career progression.",
    appTypes: ["study-permit"],
    weight: 3,
    flagOnNo: true,
    category: "hard_fail",
  },
  {
    id: "genuine_student",
    text: "Can you clearly explain how this program improves your career prospects in your home country?",
    helpText: "Officers assess whether you have genuine student intent and a reason to return. Your SOP should answer this directly.",
    appTypes: ["study-permit"],
    weight: 3,
    flagOnNo: true,
    category: "hard_fail",
  },
  {
    id: "tuition_paid",
    text: "Have you paid (or can you prove payment of) your first-year tuition?",
    helpText: "Proof of tuition payment significantly strengthens your application and demonstrates genuine intent.",
    appTypes: ["study-permit"],
    weight: 2,
    flagOnNo: false,
    boostOnYes: true,
    missingDocLabel: "Tuition Payment Proof",
    category: "weakness",
  },
];

export const ALL_QUESTIONS: Question[] = [
  ...EXPRESS_ENTRY_QUESTIONS,
  ...STUDY_PERMIT_QUESTIONS,
  ...SHARED_QUESTIONS,
];
